apiVersion: apps/v1
kind: Deployment
metadata:
  name: questcode-backend-scm
  namespace: staging
  labels:
    app: questcode-backend-scm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: questcode-backend-scm
  template:
    metadata:
      labels:
        app: questcode-backend-scm
    spec:
      containers:
      - name: questcode-backend-scm
        image: wsiqueira/backend-scm:1.0
        ports:
        - containerPort: 3020
        env:
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: questcode
              key: GITHUB_CLIENT_SECRET
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: questcode
              key: NODE_ENV
        - name: GITHUB_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: questcode
              key: GITHUB_CLIENT_ID
              