apiVersion: v1
kind: Service
metadata:
  name: questcode-frontend
  namespace: staging
spec:
  type: NodePort
  selector:
    app: questcode-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080