apiVersion: v1
kind: Service
metadata:
  name: questcode-backend-scm
  namespace: staging
spec:
  type: NodePort
  selector:
    app: questcode-backend-scm
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
      nodePort: 30030